branches:
  only:
  - master

jobs:
  stages:
    - test
    - build
    - deploy

  include:
    - stage: test
      script: ./scripts/test-backend.sh

    - stage: build
      language: node_js
      node_js:
      - node  # Current stable, i.e. 13 in October, 2019
      - lts/* # Most recent LTS version, i.e. 12 in October, 2019
      - "10"  # Explicitly include an active LTS version
      name: build-frontend
      script: ./scripts/build-frontend.sh

    - stage: build
      name: build-backend
      script: ./scripts/build-backend.sh

    - stage: deploy
      name: deploy-frontend
      deploy: 
        provider: s3
        bucket: tj-memeo-frontend
        region: us-east-2
        skip_cleanup: true
        local_dir: deploy-folder-frontend
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key:
          secure: $AWS_ACCESS_KEY

    - stage: deploy
      script: ./scripts/deploy-backend.sh
      name: deploy-backend
      deploy: 
        provider: s3
        bucket: tj-memeo-backend
        region: us-east-2
        skip_cleanup: true
        local_dir: deploy-folder-backend
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key:
          secure: $AWS_ACCESS_KEY
