branches:
  only:
  - master

env:
  global:
    MAVEN_CLI_OPTS="${REDIS_SERVER} ${MYSQL_SERVER} ${MYSQL_PASSWORD}"

jobs:
  stages:
    - test
    - build
    - deploy
    
  include:

    - stage: test
      name: test-frontend
      language: node_js
      node_js: '10'
      script: bash ./scripts/app.sh tf

    - stage: test
      name: test-backend
      language: java
      jdk: openjdk8
      script: 
        - echo $MAVEN_CLI_OPTS
        - bash ./scripts/app.sh tb $MAVEN_CLI_OPTS

    - stage: build
      name: build-frontend
      language: node_js
      node_js: '10'
      script: 
      - bash ./scripts/app.sh bf
      
    - stage: build
      name: build-backend
      language: java
      jdk: openjdk8
      script: bash ./scripts/app.sh bb $MAVEN_CLI_OPTS
      
    - stage: deploy
      name: deploy-frontend
      script:
      - bash ./scripts/app.sh bf
      - bash ./scripts/app.sh pf
      deploy:
        provider: s3
        bucket: tj-memeo-frontend
        region: us-east-2
        skip_cleanup: true
        local_dir: deploy-folder-frontend
        access_key_id: $AWS_KEY_ID
        secret_access_key: $AWS_KEY

    - stage: deploy
      name: deploy-backend
      script: 
      - bash ./scripts/app.sh bb $MAVEN_CLI_OPTS
      - bash ./scripts/app.sh pb
      deploy:
        provider: s3
        bucket: tj-memeo-backend
        region: us-east-2
        skip_cleanup: true
        local_dir: deploy-folder-backend
        access_key_id: $AWS_KEY_ID
        secret_access_key: $AWS_KEY
        