version: 0.0
os: linux
files:
  - source: /
    destination: /var/backend/memeo
hooks:
  BeforeInstall:
    - location: before-start.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start-app.sh
      timeout: 300
      runas: root